[package]
name = "bevy-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14", features = ["wayland"] }
rand = { version = "0.8.5", features = ["small_rng"] }

[features]
bevy_debug_stepping = []
