[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1", features = ["derive"] }
clap-verbosity-flag = "3.0.0"
log = "0.4.21"
env_logger = "0.11.3"
anyhow = "1.0.86"
